sudo: required
arch: amd64
dist: bionic
services:
  - docker
git:
  depth: false

language: erlang

otp_release:
 - 22.3.4
 - 23.0.4

install: "true"

env:
  global:
    - BUILD_IMAGE="ergw/ergw-c-node"
    - DOCKER_USERNAME="ergwci"
    - secure: "JpJScMSO4Sqj4odjSFEpshqFk93ZyVkhMNNc9xh2yfRpkHFNXXnhLYhKLA/nr1gcd1f9jnWz++1cqa4MQXRGanDT3+iGNO12R/M3ZVT26ywV0QEmj6z/acsv5wC34hje8/zWAgKWBsIxswFVT+RRPzNOQNVq6JPLZSp014qX5P+ChwmPeCG2kY/od9fsftp7ZjqyhqOOlXGJeEInvF5SD1RqnVMYP2OEQnGQyAHg9aoczO1cZnpZSRQFTqtDzwG1lp21oqsk2IVSCTqXdD1+GNSZCV4oHddXwGJICN9klSHUnxKb7/rFwbVh090+wP7PA+4eqCOOCGIIePFRMDiux6wX07p4wFhtt6/ZGmOs+1kV9ZR4W9FP+rv/0LUlMpmd52WoWkn1kGA/fEr/Jff3n+PjcXd25W/ASeKciahhvXLudeoauP3/wB/3gfFBSnaVR1FvU10rAdL9X+W13z+UiL5C+1qDRjs/6OFpq0T4KfWkxxy1+9eG5J5u8gsKQ+1THvSerddGX77ZvnHu1m1A8z8fGF6toMUvR7EJvr/wpeVwRO/SOB03JYUYdeRnGYXYbOt4UE2ovh/g34mnxQptKW3Pk9aqT2x/Uamsn661tRJL7kVCGOnIUohh4Ynf2tniLbWsRorZlltcIxK4kaKuNfsV/gpvAaguDkeY0ul5AqM="

before_script:
  - wget https://s3.amazonaws.com/rebar3/rebar3
  - chmod u+x ./rebar3
  # Add an IPv6 config - see the corresponding Travis issue
  # https://github.com/travis-ci/travis-ci/issues/8361
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6';
      sudo ip addr add fd96:dcd2:efdb:41c3::10/64 dev lo;
      sudo ip addr add fd96:dcd2:efdb:41c3::11/64 dev lo;
      sudo ip addr add fd96:dcd2:efdb:41c3::12/64 dev lo;
      sudo ip addr add fd96:dcd2:efdb:41c3::13/64 dev lo;
      sudo ip addr add fd96:dcd2:efdb:41c3::14/64 dev lo;
      sudo ip addr add fd96:dcd2:efdb:41c3::15/64 dev lo;
      sudo ip addr add fd96:dcd2:efdb:41c3::16/64 dev lo;
      sudo ip addr add fd96:dcd2:efdb:41c3::17/64 dev lo;
      sudo ip addr add fd96:dcd2:efdb:41c3::18/64 dev lo;
      sudo ip addr add fd96:dcd2:efdb:41c3::19/64 dev lo;
      sudo ip addr add fd96:dcd2:efdb:41c3::1a/64 dev lo;
      sudo ip addr add fd96:dcd2:efdb:41c3::20/64 dev lo;
      sudo ip addr add fd96:dcd2:efdb:41c3::30/64 dev lo;
      sudo ip addr add fd96:dcd2:efdb:41c3::40/64 dev lo;
      sudo ip addr add fd96:dcd2:efdb:41c3::50/64 dev lo;
      sudo sh -c 'echo "::1     localhost ip6-localhost ip6-loopback" >> /etc/hosts';
    fi

#script:
 # - ip -br addr
 # - source test/env.sh
 # - ./rebar3 compile
 # - ./rebar3 do xref, ct
 # - (./rebar3 as test do coveralls send || /bin/true)
 # - (cd _build/test/logs/; zip -1r ../../../ct-logs.zip . )

jobs:
  include:
    -
    # this fails, disable it for the moment
    # - dist: xenial
    #   arch: arm64
    #   otp_release: 22.0.5
    - stage: docker
      otp_release: 22.3.4
      script:
        - docker build -t $BUILD_IMAGE -f docker/Dockerfile .
      after_success:
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - export GIT_DESCRIBE=`git describe`
        - export TAG=`if [ "$TRAVIS_EVENT_TYPE" == "pull_request" ]; then echo PR-$TRAVIS_PULL_REQUEST_BRANCH\_$TRAVIS_PULL_REQUEST_SHA ; else echo $TRAVIS_BRANCH\_$GIT_DESCRIBE ; fi`
        - export TAG=`echo "$TAG" | sed -e 's,/,-,g'`
        - echo "Docker image $BUILD_IMAGE:$TAG"
        - if [ "$TAG" == "master" ]; then export TAG="latest"; fi
        - docker tag $BUILD_IMAGE $BUILD_IMAGE:$TAG
        - docker push $BUILD_IMAGE:$TAG
        - echo "docker push done"

addons:
  artifacts:
    paths: ct-logs.zip
    bucket: travis-erlang-logs
    s3_region: eu-west-1
    acl: public_read

notifications:
  webhooks: https://coveralls.io/webhook
  slack:
    secure: VMWPbtMTVKOtOtAIRPEgnN6XXKy40or/D+GMqpuFiz2JrauCao8ggcoQouX7mUMtVDqlgoJVpooCV2iyFRJbxgj/1sv/2LmC7iGALB0mR8HHkm4XpwTWBCHpf/ugiQ5jadcqEfjbVBPddJYYj2k9GxCB4Aiu1d+NyLOuPk58jiXHztfmSiU1XEwNbAq843BTKuEDx/A+Zk/gmZs4Is7j6uuSXhp6+EC+46cDeLq7w1ejVquQgHkk3Yy9NNUjRYmcCbhVqKDb7bkhFnBr6Tt+O3ljzILWFqsnKDQ1CAAdudmYJYR9OUGdmle/0Nwpw/D7hP4ZiNWPVcXeZA6QwXG+46iZ1YlT+45wBb5GrhZnF1zcd8HRA2a3MkTkLci/3/v19GtrRa3G61LdocnmvanpAzN+sSpXlZvkQI2i5s1hgd+L08YkOxXSZxmkcV2Nh2IC8SNMx+sc8Ftrj9sffbznfp1rljDqXP4eKdIoJvBnFdrzUuDR/1/sZ4K/YXj80XdAAANNfebTdE6k2NbZ+YGJADQLxi3Nl7I/66HMSIequaKFIlU8MQairvo4jZgbytuZk8ndOLhR0/04Teb0k8ltNq8OQMV5nRHjznfqVvj1cJIhzvn6WbG2zFiRGiWL9U9XaktA1uHTuV37GRPetIZq1WnMmjH7lEQvGYnqPh/sMt0=
